- name: task level variables
  hosts: local
  connection: local
  vars:
   course: aws
   duration: 10
   trainer: siva
  tasks:
  - name: print the course details
    vars:
      course: devops with cloude
    ansible.builtin.debug:
      msg: "the course name is {{ course }}, duration is : {{ duration }}"
