- name: prompt variables
  hosts: local
  connection: local
  vars_promt:
   - name: username
     prompt: what is your username?
     private: false
  tasks:
   - name: print credentials
     ansible.builtin.debug:
       msg: "the user name is {{ username }}"